In [4]:
import tensorflow as tf
import os

In [5]:
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
print(tf.version)

<module 'tensorflow._api.v2.version' from 'C:\\Users\\PC\\anaconda3\\envs\\s2m\\lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


# Initialization

Mannual

In [11]:
x = tf.constant(4,shape=(1,1), dtype=tf.float32);
print(x);
x = tf.constant([[1,2,3],[4,5,6]]);
print(x);

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


Auto

In [12]:
x = tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [13]:
x = tf.zeros((4,3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(4, 3), dtype=float32)


In [14]:
x = tf.eye((5))
print(x)

tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)


In [15]:
x = tf.random.normal((3,3), mean=0, stddev=1)
print(x)

tf.Tensor(
[[-1.9678732   2.3979218  -1.3068689 ]
 [ 0.81524384 -0.7369255  -1.00357   ]
 [ 0.04697453 -1.0692445   0.6929658 ]], shape=(3, 3), dtype=float32)


In [16]:
x = tf.random.uniform((4,3), minval=0, maxval=1)
print(x)

tf.Tensor(
[[0.44088674 0.01553476 0.9015616 ]
 [0.28620934 0.8942772  0.28065717]
 [0.22289968 0.00873804 0.61519885]
 [0.5962297  0.7407788  0.03315246]], shape=(4, 3), dtype=float32)


In [19]:
x = tf.range(start=1, limit=10, delta=2)
print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [20]:
x = tf.range(start=1, limit=10, delta=2)
print(x)
x = tf.cast(x, dtype=tf.float32)
print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)
tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float32)


# Mathematical operations

In [24]:
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])
z = tf.add(x,y)
print(z)
z= x + y #equivalent and convienient
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [27]:
x = tf.constant([19, 18, 17])
y = tf.constant([9, 8, 7])
z = tf.subtract(x,y)
print(z)
z= x - y #equivalent and convienient
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [29]:
x = tf.constant([20, 16, 21])
y = tf.constant([2, 2, 3])
z = tf.divide(x,y)
print(z)
z= x / y #equivalent and convienient
print(z)

tf.Tensor([10.  8.  7.], shape=(3,), dtype=float64)
tf.Tensor([10.  8.  7.], shape=(3,), dtype=float64)


In [30]:
x = tf.constant([5, 8, 7])
y = tf.constant([2, 2, 3])
z = tf.multiply(x,y)
print(z)
z= x * y #equivalent and convienient
print(z)

tf.Tensor([10 16 21], shape=(3,), dtype=int32)
tf.Tensor([10 16 21], shape=(3,), dtype=int32)


In [32]:
x = tf.constant([5, 8, 7])
y = tf.constant([2, 2, 3])
z = tf.tensordot(x,y, axes=1) #Dot multiply + summation
print(z)

tf.Tensor(47, shape=(), dtype=int32)


In [33]:
x = tf.constant([5, 8, 7])
y = tf.constant([2, 2, 3])
z = tf.reduce_sum(x*y, axis=0)
print(z)

tf.Tensor(47, shape=(), dtype=int32)


In [35]:
x = tf.constant([5, 8, 7])
z = x ** 2
print(z)

tf.Tensor([25 64 49], shape=(3,), dtype=int32)


In [37]:
x = tf.random.uniform((4,3), minval=1, maxval=10)
y = tf.random.uniform((3,4), minval=1, maxval=10)
z = tf.matmul(x, y)
print(z)
z = x @ y
print(z)

tf.Tensor(
[[ 59.193535  19.81967   66.89896   43.71739 ]
 [125.93254   41.570908 145.50398   92.54862 ]
 [ 60.328156  23.343624  98.177765  72.67149 ]
 [ 96.07788   29.90311  129.1406    73.84709 ]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[ 59.193535  19.81967   66.89896   43.71739 ]
 [125.93254   41.570908 145.50398   92.54862 ]
 [ 60.328156  23.343624  98.177765  72.67149 ]
 [ 96.07788   29.90311  129.1406    73.84709 ]], shape=(4, 4), dtype=float32)


# Indexing

In [43]:
x = tf.constant([0,1,2,3,4,5,6,7,8,9,10])
print(x[:])

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10], shape=(11,), dtype=int32)


In [44]:
x = tf.constant([0,1,2,3,4,5,6,7,8,9,10])
print(x[1:])

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10], shape=(10,), dtype=int32)


In [45]:
x = tf.constant([0,1,2,3,4,5,6,7,8,9,10])
print(x[2:])

tf.Tensor([ 2  3  4  5  6  7  8  9 10], shape=(9,), dtype=int32)


In [46]:
x = tf.constant([0,1,2,3,4,5,6,7,8,9,10])
print(x[1:3]) #3 not inclusive

tf.Tensor([1 2], shape=(2,), dtype=int32)


In [48]:
x = tf.constant([0,1,2,3,4,5,6,7,8,9,10])
print(x[::2]) # skip every other element

tf.Tensor([ 0  2  4  6  8 10], shape=(6,), dtype=int32)


In [49]:
x = tf.constant([0,1,2,3,4,5,6,7,8,9,10])
print(x[::5]) # skip every other element

tf.Tensor([ 0  5 10], shape=(3,), dtype=int32)


In [50]:
x = tf.constant([0,1,2,3,4,5,6,7,8,9,10])
print(x[::-1]) #print in reverse

tf.Tensor([10  9  8  7  6  5  4  3  2  1  0], shape=(11,), dtype=int32)


In [53]:
x = tf.constant([1,10,20,30,40,50,60,70,80,90,100])
indices = tf.constant([0,10])
element = tf.gather(x,indices) # get the elements in index 0 and 10 specified in indices tensor
print(element) 

tf.Tensor([  1 100], shape=(2,), dtype=int32)


In [58]:
x = tf.constant([[1,10],
                [2,20],
                [3,30]])
print(x) # Whole tensor
print(x[0]) # First array in tensor
print(x[0,:]) # All elements of first array in tensor
print(x[0,1:]) # Second element to end of first array in tensor
print(x[:2,:]) # All elements of first array and second array in tensor
print(x[:2,:1]) # First elements of first array and second array in tensor

tf.Tensor(
[[ 1 10]
 [ 2 20]
 [ 3 30]], shape=(3, 2), dtype=int32)
tf.Tensor([ 1 10], shape=(2,), dtype=int32)
tf.Tensor([ 1 10], shape=(2,), dtype=int32)
tf.Tensor([10], shape=(1,), dtype=int32)
tf.Tensor(
[[ 1 10]
 [ 2 20]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1]
 [2]], shape=(2, 1), dtype=int32)


# Reshaping

In [63]:
x = tf.range(9)
print(x)
x = tf.reshape(x,(3,3))
print(x)
x = tf.reshape(x,(9,1))
print(x)
x = tf.reshape(x,(1,9))
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]], shape=(9, 1), dtype=int32)
tf.Tensor([[0 1 2 3 4 5 6 7 8]], shape=(1, 9), dtype=int32)


In [66]:
x = tf.constant([[1,10],
                [2,20],
                [3,30]])
print(x)
x = tf.transpose(x,perm=[1,0])
print(x)

tf.Tensor(
[[ 1 10]
 [ 2 20]
 [ 3 30]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 1  2  3]
 [10 20 30]], shape=(2, 3), dtype=int32)
