## Creez une liste Python

In [9]:
revenus = [1800, 1500, 2200, 3000, 2172]

In [10]:
print(revenus)

[1800, 1500, 2200, 3000, 2172]


In [11]:
#print(revenus.mean()) NOT WORKING
import numpy as np
print(np.mean(revenus))

2134.4


In [12]:
x = [-2, -1, 1, 2]
print("La valeur absolue: ", np.abs(x))
print("Exponentielle: ", np.exp(x))
print("Logarithme: ", np.log(np.abs(x)))

La valeur absolue:  [2 1 1 2]
Exponentielle:  [0.13533528 0.36787944 2.71828183 7.3890561 ]
Logarithme:  [0.69314718 0.         0.         0.69314718]


## Créez un array NumPy

In [13]:
revenus_array = np.array(revenus)
revenus_array

array([1800, 1500, 2200, 3000, 2172])

## Créez un array NumPy predefinis 

In [14]:
print(np.zeros(10)) #: permet de créer un array rempli de 0, de n éléments ;
print(np.ones(10)) # : similaire en tous points à la fonction présentée ci-dessus, à la différence que l’array sera rempli cette fois-ci de 1 ;
print(np.arange(100, 2000, 200)) #  : permet de créer un array rempli avec une séquence linéaire, qui ira de  i  à  j, par pas de  p  ;
print(np.linspace(0, 77, 10)) # : permet de créer un array de  n  valeurs espacées uniformément entre  i  et  j.

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 100  300  500  700  900 1100 1300 1500 1700 1900]
[ 0.          8.55555556 17.11111111 25.66666667 34.22222222 42.77777778
 51.33333333 59.88888889 68.44444444 77.        ]


## Créez un array monotype

Comme nous avons pu le voir précédemment, un array ne peut contenir qu’un seul et unique type. Vous pouvez accéder au type des éléments d’un array via la méthode  .dtype  :

In [15]:
revenus_array.dtype
# dtype('int32')

dtype('int32')

## Sélectionnez des éléments au sein d’un array

### Accédez à un seul élément

In [17]:
print(revenus_array[4])  # pour accéder au 5ème élement
print(revenus_array[-1]) # pour accéder au dernier élément
revenus_array[1] = 1900# On peut aussi modifier les valeurs
print(revenus_array[1])

2172
2172
1900


### Accédez à plusieurs éléments contigus

Nous pouvons accéder à un ensemble d'éléments contigus en combinant []  et  : . La syntaxe suit une règle simple : nom_array[i:j:p] , avec :

=> i  : l’indice du début.  
=>j  : l’indice de fin.  
=>p : le pas.  
permettant de sélectionner tous les éléments compris entre l’indice  i  inclus, jusqu’à  j-1   – l’élément d’indice  j  est forcément exclu.

In [18]:
revenus_array[0:3] #permet de sélectionner, au sein de notre array  revenus_array , l’ensemble des éléments de l’indice 0 
#(soit le premier élément) jusqu’à celui d’indice 2 (soit le troisième). L’élément d’indice 3 n’est pas inclus !
#Si vous souhaitez également le sélectionner, il faudra ajouter 1 à l’indice de fin : revenus_array[0:4] .

array([1800, 1900, 2200])

Le début peut être omis si on veut commencer au début de la liste (c'est-à-dire si début = 0). La fin peut être omise si on veut aller jusqu'au bout de la liste (c'est-à-dire fin = -1 ou fin =  len(liste)  ). Le pas, ainsi que le dernier  :  , peuvent être omis si le pas est de 1 (-1 si la fin est inférieure au début).

In [29]:
print(revenus_array)
print(revenus_array[:3])# Les 3 premiers éléments
print(revenus_array[0:3])# Les 3 premiers éléments
print(revenus_array[2:]) # Les éléments à partir de l’indice 2
print(revenus_array[2:len(revenus_array)]) # Les éléments à partir de l’indice 2
print(revenus_array[::2]) # Un élément sur deux
print(revenus_array[::-1]) # Reversed

[1800 1900 2200 3000 2172]
[1800 1900 2200]
[1800 1900 2200]
[2200 3000 2172]
[2200 3000 2172]
[1800 2200 2172]
[2172 3000 2200 1900 1800]


### Accédez à plusieurs éléments selon une condition

On peut cependant souhaiter aller plus loin dans l’accès aux différents éléments. En effet, lors d’une étude de données on est régulièrement amené à devoir sélectionner une partie de nos données, selon un critère (ex. un genre spécifique) ou une condition (ex. toutes les personnes en dessous d’un certain âge). Les arrays NumPy permettent de faire cela !

En effet, de la même façon qu’il est possible de sélectionner des éléments via leur indice, il est possible avec les arrays NumPy de renseigner la condition selon laquelle on souhaite sélectionner les éléments du tableau, avec l’écriture  nom_array[condition de sélection]  .

Voilà par exemple comment sélectionner uniquement les valeurs supérieures à 2 000 € :

In [30]:
revenus_array[revenus_array > 2000] # array([2200, 3000, 2172])

array([2200, 3000, 2172])

Détaillons le fonctionnement de ce processus de sélection :

tout d’abord, on cite explicitement le nom de l’array avant les crochets, pour spécifier dans quel array on souhaite effectuer la sélection ;

ensuite, on spécifie à l’intérieur des crochets la condition. Le résultat de ce qui est à l’intérieur des crochets doit forcément être un array ou une liste de booléens ! Ici, si on exécute uniquement la condition  revenus_array > 2000 , vous verrez que vous aurez simplement un array contenant uniquement des booléens, avec True  lorsque la valeur satisfait la condition, False  sinon.

In [32]:
print(revenus_array > 2000)

[False False  True  True  True]


In [33]:
revenus_array[[False, False,True,True,True]]

array([2200, 3000, 2172])

In [34]:
revenus_array[(revenus_array > 2000) & (revenus_array < 3000)] # array([2200, 2172])

array([2200, 2172])

Le et logique (respectivement ou logique) n’est pas matérialisé par le mot clé "and" (respectivement "or") comme dans une structure conditionnelle if  classique, mais par le symbole  &   (respectivement  "|"). De plus, chaque condition doit être absolument délimitée par des parenthèses, sous peine de rencontrer une erreur. Cette écriture s’explique par le fait qu’on ne compare pas des booléens, mais des arrays de booléens, terme à terme.  

### Accédez à plusieurs éléments selon une condition

Il est à noter que cette syntaxe ne permet pas uniquement de sélectionner des éléments, mais qu'elle peut également être utilisée pour modifier des éléments au sein d’un array. En effet, si vous exécutez :

In [35]:
revenus_array[revenus_array > 2000] = 0 
print(revenus_array)

[1800 1900    0    0    0]


vous remplacerez tous les éléments supérieurs à 2 000 au sein de notre array par 0. Il faut donc être vigilant en utilisant cette syntaxe, pour ne pas remplacer des valeurs qu’il n’aurait pas été souhaitable de remplacer.

### Utilisez les méthodes d’array

In [39]:
print(revenus_array.dtype)
print(revenus_array.shape) #accéder facilement aux dimensions de notre array 
print(revenus_array.mean()) #calculer la moyenne
print(revenus_array.min()) #calculer le minimum
print(revenus_array.max()) #calculer le maximum
print(revenus_array.argmin()) #trouver lindice de lelement minimum
print(revenus_array.argmax()) #trouver lindice de lelement maximum
revenus_array ; revenus_array.sort(); print(revenus_array) #trie
print(revenus_array.sum()) # somme

int32
(5,)
740.0
0
1900
0
4
[   0    0    0 1800 1900]
3700
